// @ts-expect-error: this type will be autogenerated
import type { APIBitwiseEnum } from "./dist/apis.d.ts";

import type { proxifiedObjType } from "./apiInterceptors";

export default interface ToBeDefined {
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	defineProperty: any;
	window: {
		globalProp: string;
		// biome-ignore lint/suspicious/noExplicitAny: <explanation>
		self: any;
		proxyObject: proxifiedObjType;
	};
}

/** Key: name of API Interceptor
 * Value: the error when trying to load the API interceptor */

export type toBeDefinedErrsType = { [key: keyof APIBitwiseEnum]: Error };
