// Auto-generated by webidl2ts - https://wicg.github.io/web-app-launch/
interface LaunchParams {
	readonly targetURL: string;
	readonly files: ReadonlyArray<FileSystemHandle>;
}
declare var LaunchParams: LaunchParams;
type LaunchConsumer = (params: LaunchParams) => any;
interface Window {
	readonly launchQueue: LaunchQueue;
}
interface LaunchQueue {
	setConsumer(consumer: LaunchConsumer): undefined;
}
declare var LaunchQueue: LaunchQueue;
