import { writeFileSync } from "node:fs";

import createDefaultFeatureFlags from "../createDefaultFeatureFlags";
import featureFlagsBuilder from "../featureFlagsBuilder";

import type { Result } from "neverthrow";
import { err as errr, ok } from "neverthrow";

export default function initGlobalsTs(
	output: "../types/dist/globals.d.ts",
): Result<void, Error> {
	const featureFlags = featureFlagsBuilder(createDefaultFeatureFlags({
		debugMode: true,
	}));

	const lines: string[] = ["declare global {"];
	for (const [featureFlag, val] of Object.entries(featureFlags)) {
		try {
			// @ts-ignore: it could be anything. There is a try statement if something goes wrong anyways
			const valType = typeof JSON.parse(val);
			if (valType === "number" || valType === "string") {
				lines.push(`\tconst ${featureFlag}: ${valType};`);
			} else {
				return errr(
					new SyntaxError(
						`Unexpected type for feature flag, ${featureFlag}, ${valType}`,
					),
				);
			}
		} catch (err) {
			return errr(err);
		}
	}
	lines.push("}");

	writeFileSync(
		output,
		`// Autogenerated by \`initGlobalsTs.ts\`\n${lines.join("\n")}`,
		{
			flag: "w",
		},
	);

	// @ts-ignore
	return ok();
}
